#!/usr/bin/env python3
"""Generate data/districts-data.json for DropTaxi district pages."""
import json, os, math

AIRPORTS = {
    "MAA": "Chennai International Airport",
    "CJB": "Coimbatore International Airport",
    "IXM": "Madurai Airport",
    "TRZ": "Tiruchirappalli International Airport",
    "TRV": "Trivandrum International Airport",
    "COK": "Cochin International Airport",
    "CCJ": "Calicut International Airport",
    "IXE": "Mangalore International Airport",
    "BLR": "Kempegowda International Airport Bangalore",
    "HYD": "Rajiv Gandhi International Airport Hyderabad",
    "VTZ": "Visakhapatnam Airport",
    "TIR": "Tirupati Airport",
    "VGA": "Vijayawada Airport",
    "HBX": "Hubli Airport",
    "IXU": "Aurangabad Airport",
    "RJA": "Rajahmundry Airport",
    "CDP": "Kadapa Airport",
    "KLO": "Kannur International Airport",
}

def parse_routes(s):
    routes = []
    for r in s.split("|"):
        parts = r.split(":")
        routes.append({"to": parts[0], "toSlug": parts[1], "distanceKm": int(parts[2]), "durationHrs": float(parts[3])})
    return routes

def generate_faqs(name, slug, state, routes):
    r0 = routes[0]
    fare_sedan = r0["distanceKm"] * 13 + 300
    fare_suv = r0["distanceKm"] * 19 + 400
    r1 = routes[1] if len(routes) > 1 else r0
    return [
        {"q": f"What is the drop taxi fare from {name} to {r0['to']}?",
         "a": f"The sedan fare starts at approximately ₹{fare_sedan:,}. SUV fare starts at ₹{fare_suv:,}. Fares include driver bata and fuel. Toll and parking charges are extra."},
        {"q": f"Is night drop taxi available from {name}?",
         "a": f"Yes, DropTaxi operates 24/7 from {name}. Night bookings between 10 PM and 6 AM are available with verified, experienced drivers for safe travel."},
        {"q": f"What car types are available for drop taxi in {name}?",
         "a": f"We offer AC Sedan (Etios/Dzire), SUV (Innova/Ertiga), and Tempo Traveller for group bookings. All vehicles are well-maintained and GPS-tracked."},
        {"q": f"How do I book a one way taxi from {name}?",
         "a": f"Call 063838 83922 or WhatsApp us with your pickup point in {name}, drop destination, travel date, and car preference. You will get instant fare confirmation."},
        {"q": f"Can I book a drop taxi from {name} to {r1['to']}?",
         "a": f"Yes, {name} to {r1['to']} is a popular route. The distance is approximately {r1['distanceKm']} km and takes about {r1['durationHrs']} hours. Book via call or WhatsApp for best rates."},
    ]

def make_entry(slug, name, state, st_short, apt_code, apt_dist, pickups, routes_str, nearby, popular_for):
    routes = parse_routes(routes_str)
    return {
        "slug": slug, "name": name, "state": state, "stateShort": st_short,
        "nearestAirport": {"name": AIRPORTS.get(apt_code, apt_code), "code": apt_code, "distanceKm": apt_dist},
        "pickupPoints": pickups.split("|"),
        "routes": routes,
        "nearbyDistricts": nearby.split("|"),
        "popularFor": popular_for,
        "uniqueFaqs": generate_faqs(name, slug, state, routes),
    }

# ─── TAMIL NADU DISTRICTS ─────────────────────────────────────────
TN = "Tamil Nadu"
TN_DATA = [
    ("ariyalur", "Ariyalur", "TRZ", 55,
     "Ariyalur Bus Stand|Ariyalur Railway Station|Sendurai|Jayamkondam",
     "Trichy:trichy:30:0.5|Thanjavur:thanjavur:60:1.5|Perambalur:perambalur:25:0.5|Chennai:chennai:300:5|Kumbakonam:kumbakonam:80:2",
     "perambalur|trichy|thanjavur|cuddalore|kallakurichi",
     "Ancient Chola temples, limestone quarries, agricultural town"),
    ("chengalpattu", "Chengalpattu", "MAA", 45,
     "Chengalpattu Bus Stand|Chengalpattu Railway Station|Mahabalipuram|GST Road Junction",
     "Chennai:chennai:55:1.5|Mahabalipuram:mahabalipuram:30:0.5|Kanchipuram:kanchipuram:30:0.5|Pondicherry:pondicherry:110:2.5|Vellore:vellore:130:2.5",
     "chennai|kanchipuram|villupuram|tiruvallur|ranipet",
     "Mahabalipuram Shore Temple, Vedanthangal bird sanctuary, gateway to ECR"),
    ("chennai", "Chennai", "MAA", 15,
     "Chennai Central Railway Station|Tambaram|Guindy|OMR|T Nagar|Koyambedu Bus Stand",
     "Bangalore:bangalore:350:6|Coimbatore:coimbatore:510:8|Madurai:madurai:460:7|Trichy:trichy:330:5|Vellore:vellore:140:2.5|Pondicherry:pondicherry:150:3|Tirupati:tirupati:135:3",
     "chengalpattu|kanchipuram|tiruvallur|ranipet",
     "IT hub, Marina Beach, temples, gateway to South India"),
    ("coimbatore", "Coimbatore", "CJB", 12,
     "Coimbatore Junction Railway Station|Gandhipuram Bus Stand|RS Puram|Ukkadam|Singanallur",
     "Chennai:chennai:510:8|Ooty:ooty:90:2.5|Bangalore:bangalore:365:6|Madurai:madurai:220:4|Salem:salem:160:3|Palakkad:palakkad:55:1|Trichy:trichy:220:4|Pollachi:pollachi:40:1",
     "tirupur|erode|nilgiris|palakkad|dindigul|karur",
     "Manchester of South India, textile hub, gateway to Ooty and Munnar"),
    ("cuddalore", "Cuddalore", "MAA", 180,
     "Cuddalore Bus Stand|Cuddalore Railway Station|Chidambaram|Silver Beach",
     "Pondicherry:pondicherry:25:0.5|Chennai:chennai:185:3.5|Trichy:trichy:150:3|Nagapattinam:nagapattinam:80:2|Villupuram:villupuram:35:1",
     "villupuram|nagapattinam|mayiladuthurai|kallakurichi|chidambaram",
     "Chidambaram Nataraja Temple, Silver Beach, French colonial heritage"),
    ("dharmapuri", "Dharmapuri", "BLR", 130,
     "Dharmapuri Bus Stand|Dharmapuri Railway Station|Hogenakkal|Pennagaram",
     "Salem:salem:65:1.5|Bangalore:bangalore:200:3.5|Krishnagiri:krishnagiri:55:1|Hosur:hosur:100:2|Chennai:chennai:300:5",
     "salem|krishnagiri|tiruvannamalai|erode|tirupattur",
     "Hogenakkal Falls, mango orchards, scenic granite hills"),
    ("dindigul", "Dindigul", "IXM", 65,
     "Dindigul Bus Stand|Dindigul Junction|Palani|Kodaikanal Road",
     "Madurai:madurai:65:1.5|Kodaikanal:kodaikanal:80:2.5|Trichy:trichy:100:2|Coimbatore:coimbatore:200:3.5|Palani:palani:25:0.5",
     "madurai|theni|karur|sivagangai|trichy|palani",
     "Dindigul Fort, lock-making capital, gateway to Kodaikanal"),
    ("erode", "Erode", "CJB", 80,
     "Erode Bus Stand|Erode Junction Railway Station|Perundurai|Bhavani|Gobichettipalayam",
     "Coimbatore:coimbatore:100:2|Salem:salem:65:1.5|Tirupur:tirupur:50:1|Chennai:chennai:400:6.5|Ooty:ooty:155:3.5",
     "tirupur|coimbatore|salem|namakkal|karur",
     "Turmeric city, handloom textiles, Bhavani Sangameshwar Temple"),
    ("kallakurichi", "Kallakurichi", "MAA", 220,
     "Kallakurichi Bus Stand|Chinnasalem|Ulundurpet|Sankarapuram",
     "Salem:salem:110:2|Villupuram:villupuram:50:1|Chennai:chennai:250:4.5|Pondicherry:pondicherry:110:2.5|Trichy:trichy:170:3",
     "villupuram|salem|cuddalore|dharmapuri|tiruvannamalai",
     "Agricultural district, scenic Eastern Ghats, jackfruit orchards"),
    ("kanchipuram", "Kanchipuram", "MAA", 65,
     "Kanchipuram Bus Stand|Kanchipuram Railway Station|Enathur|Uthiramerur",
     "Chennai:chennai:75:1.5|Chengalpattu:chengalpattu:30:0.5|Vellore:vellore:70:1.5|Pondicherry:pondicherry:95:2|Tiruvannamalai:tiruvannamalai:90:2",
     "chengalpattu|chennai|tiruvallur|ranipet|vellore|villupuram",
     "City of 1000 Temples, silk saree capital, UNESCO Pallava monuments"),
    ("kanyakumari", "Kanyakumari", "TRV", 85,
     "Nagercoil Bus Stand|Kanyakumari Railway Station|Nagercoil Junction|Marthandam",
     "Trivandrum:trivandrum:90:2|Tirunelveli:tirunelveli:70:1.5|Madurai:madurai:250:4.5|Thoothukudi:thoothukudi:150:3|Nagercoil:nagercoil:20:0.5",
     "tirunelveli|tenkasi|trivandrum|thoothukudi",
     "Southernmost tip of India, Vivekananda Rock, sunrise/sunset point"),
    ("karur", "Karur", "TRZ", 80,
     "Karur Bus Stand|Karur Junction Railway Station|Kulithalai|Aravakurichi",
     "Trichy:trichy:75:1.5|Coimbatore:coimbatore:170:3|Dindigul:dindigul:75:1.5|Salem:salem:100:2|Erode:erode:95:2|Madurai:madurai:140:2.5",
     "trichy|dindigul|namakkal|erode|tirupur",
     "Bus body building capital, textile exports, Pasupatheeswara Temple"),
    ("krishnagiri", "Krishnagiri", "BLR", 90,
     "Krishnagiri Bus Stand|Hosur|Pochampalli|Kaveripattinam",
     "Bangalore:bangalore:100:2|Hosur:hosur:45:1|Salem:salem:100:2|Dharmapuri:dharmapuri:55:1|Vellore:vellore:120:2.5|Chennai:chennai:270:4.5",
     "dharmapuri|vellore|tiruvannamalai|tirupattur|hosur",
     "Mango capital of India, KRP Dam, gateway to Bangalore from TN"),
    ("madurai", "Madurai", "IXM", 12,
     "Madurai Junction Railway Station|Periyar Bus Stand|Mattuthavani Bus Stand|Anna Nagar|Goripalayam",
     "Chennai:chennai:460:7|Trichy:trichy:130:2.5|Coimbatore:coimbatore:220:4|Bangalore:bangalore:440:7|Rameshwaram:rameshwaram:175:3.5|Kodaikanal:kodaikanal:120:3|Tirunelveli:tirunelveli:160:3",
     "dindigul|theni|sivagangai|virudhunagar|ramanathapuram|trichy",
     "Meenakshi Amman Temple, 2500-year-old temple city, cultural capital of Tamil Nadu"),
    ("mayiladuthurai", "Mayiladuthurai", "TRZ", 100,
     "Mayiladuthurai Bus Stand|Mayiladuthurai Junction|Sirkali|Poompuhar",
     "Thanjavur:thanjavur:40:1|Trichy:trichy:95:2|Kumbakonam:kumbakonam:30:0.5|Nagapattinam:nagapattinam:30:0.5|Chennai:chennai:280:5",
     "thanjavur|nagapattinam|cuddalore|trichy|kumbakonam",
     "Mayuranathaswamy Temple, Poompuhar ancient port, Cauvery delta region"),
    ("nagapattinam", "Nagapattinam", "TRZ", 120,
     "Nagapattinam Bus Stand|Nagapattinam Railway Station|Velankanni|Karaikal",
     "Velankanni:velankanni:12:0.5|Thanjavur:thanjavur:80:2|Trichy:trichy:145:3|Mayiladuthurai:mayiladuthurai:30:0.5|Chennai:chennai:310:5.5",
     "mayiladuthurai|thanjavur|tiruvarur|karaikal|cuddalore",
     "Velankanni Basilica, coastal heritage, Nagore Dargah"),
    ("namakkal", "Namakkal", "CJB", 130,
     "Namakkal Bus Stand|Rasipuram|Tiruchengode|Paramathi",
     "Salem:salem:45:1|Trichy:trichy:100:2|Erode:erode:55:1|Coimbatore:coimbatore:160:3|Karur:karur:45:1",
     "salem|erode|karur|trichy|dindigul",
     "Namakkal Fort, transport hub, poultry and egg capital of India"),
    ("perambalur", "Perambalur", "TRZ", 40,
     "Perambalur Bus Stand|Perambalur Railway Station|Kunnam|Veppanthattai",
     "Trichy:trichy:50:1|Ariyalur:ariyalur:25:0.5|Salem:salem:130:2.5|Thanjavur:thanjavur:80:2|Chennai:chennai:290:5",
     "ariyalur|trichy|salem|namakkal|karur",
     "Smallest district in TN, Sathanur Dam, ancient Chola region"),
    ("pudukkottai", "Pudukkottai", "TRZ", 55,
     "Pudukkottai Bus Stand|Pudukkottai Railway Station|Aranthangi|Karambakudi",
     "Trichy:trichy:55:1|Thanjavur:thanjavur:50:1|Madurai:madurai:130:2.5|Sivagangai:sivagangai:45:1|Rameshwaram:rameshwaram:160:3",
     "trichy|thanjavur|sivagangai|ramanathapuram|dindigul",
     "Former princely state, Sittanavasal Jain caves, ancient temples"),
    ("ramanathapuram", "Ramanathapuram", "IXM", 130,
     "Ramanathapuram Bus Stand|Ramanathapuram Railway Station|Paramakudi|Rameswaram",
     "Rameshwaram:rameshwaram:55:1|Madurai:madurai:180:3|Sivagangai:sivagangai:60:1.5|Trichy:trichy:200:3.5|Thoothukudi:thoothukudi:140:2.5",
     "sivagangai|pudukkottai|virudhunagar|thoothukudi",
     "Gateway to Rameswaram, Pamban Bridge, pilgrimage hub"),
    ("ranipet", "Ranipet", "MAA", 110,
     "Ranipet Bus Stand|Ranipet Railway Station|Walajapet|Arcot",
     "Vellore:vellore:25:0.5|Chennai:chennai:120:2.5|Kanchipuram:kanchipuram:55:1|Tiruvannamalai:tiruvannamalai:65:1.5|Bangalore:bangalore:230:4",
     "vellore|kanchipuram|tiruvannamalai|tiruvallur|chengalpattu",
     "Leather exports hub, Arcot Nawab heritage, Ranipet Fort"),
    ("salem", "Salem", "BLR", 160,
     "Salem Junction Railway Station|Salem New Bus Stand|Omalur|Mettur|Attur",
     "Chennai:chennai:340:5.5|Bangalore:bangalore:210:3.5|Coimbatore:coimbatore:160:3|Trichy:trichy:140:2.5|Erode:erode:65:1.5|Yercaud:yercaud:30:1|Madurai:madurai:230:4",
     "namakkal|dharmapuri|erode|kallakurichi|krishnagiri|tiruvannamalai",
     "Mango city, Yercaud hill station, Mettur Dam, steel hub"),
    ("sivagangai", "Sivagangai", "IXM", 90,
     "Sivagangai Bus Stand|Karaikudi|Devakottai|Chettinad",
     "Madurai:madurai:50:1|Trichy:trichy:100:2|Rameshwaram:rameshwaram:120:2.5|Karaikudi:karaikudi:12:0.5|Pudukkottai:pudukkottai:45:1|Chennai:chennai:430:7",
     "madurai|pudukkottai|ramanathapuram|virudhunagar|dindigul",
     "Chettinad palace heritage, Karaikudi cuisine, Pillaiyarpatti temple"),
    ("tenkasi", "Tenkasi", "IXM", 160,
     "Tenkasi Bus Stand|Tenkasi Railway Station|Courtallam|Sankarankovil",
     "Tirunelveli:tirunelveli:55:1|Madurai:madurai:180:3|Thoothukudi:thoothukudi:110:2|Trivandrum:trivandrum:200:4|Courtallam:courtallam:5:0.2",
     "tirunelveli|virudhunagar|thoothukudi|kanyakumari|kollam",
     "Courtallam waterfalls (Spa of South India), scenic Western Ghats"),
    ("thanjavur", "Thanjavur", "TRZ", 60,
     "Thanjavur Bus Stand|Thanjavur Junction|Big Temple|Medical College Road",
     "Trichy:trichy:55:1|Kumbakonam:kumbakonam:35:0.5|Madurai:madurai:180:3|Chennai:chennai:340:5.5|Nagapattinam:nagapattinam:80:2|Velankanni:velankanni:90:2",
     "trichy|pudukkottai|nagapattinam|mayiladuthurai|ariyalur",
     "UNESCO Brihadeeswarar Temple, rice bowl of TN, classical arts capital"),
    ("theni", "Theni", "IXM", 80,
     "Theni Bus Stand|Periyakulam|Bodinayakanur|Uthamapalayam",
     "Madurai:madurai:75:1.5|Kodaikanal:kodaikanal:65:2|Munnar:munnar:80:3|Dindigul:dindigul:90:2|Coimbatore:coimbatore:250:4.5",
     "madurai|dindigul|idukki|virudhunagar",
     "Gateway to Meghamalai and Munnar, cardamom hills, Vaigai Dam"),
    ("thoothukudi", "Thoothukudi", "IXM", 100,
     "Thoothukudi Bus Stand|Thoothukudi Junction|Tiruchendur|VOC Port",
     "Madurai:madurai:150:2.5|Tirunelveli:tirunelveli:50:1|Rameshwaram:rameshwaram:180:3|Kanyakumari:kanyakumari:150:3|Chennai:chennai:600:9",
     "tirunelveli|ramanathapuram|virudhunagar|tenkasi",
     "VOC Port, Tiruchendur Murugan Temple, salt pans, pearl city"),
    ("trichy", "Tiruchirappalli", "TRZ", 8,
     "Trichy Junction Railway Station|Central Bus Stand|Srirangam|Chatram Bus Stand|KK Nagar",
     "Chennai:chennai:330:5|Madurai:madurai:130:2.5|Coimbatore:coimbatore:220:4|Thanjavur:thanjavur:55:1|Salem:salem:140:2.5|Bangalore:bangalore:350:6",
     "ariyalur|perambalur|pudukkottai|thanjavur|karur|dindigul",
     "Rock Fort Temple, Srirangam, education hub, central TN gateway"),
    ("tirunelveli", "Tirunelveli", "IXM", 130,
     "Tirunelveli Junction|Tirunelveli Bus Stand|Palayamkottai|Ambasamudram",
     "Madurai:madurai:160:3|Kanyakumari:kanyakumari:70:1.5|Thoothukudi:thoothukudi:50:1|Tenkasi:tenkasi:55:1|Trivandrum:trivandrum:160:3",
     "tenkasi|thoothukudi|kanyakumari|virudhunagar",
     "Nellaiappar Temple, halwa city, Papanasam Dam, South TN hub"),
    ("tirupattur", "Tirupattur", "BLR", 120,
     "Tirupattur Bus Stand|Tirupattur Railway Station|Ambur|Vaniyambadi",
     "Vellore:vellore:45:1|Bangalore:bangalore:190:3|Chennai:chennai:200:3.5|Krishnagiri:krishnagiri:75:1.5|Tiruvannamalai:tiruvannamalai:60:1.5",
     "vellore|krishnagiri|dharmapuri|tiruvannamalai|ranipet",
     "Leather industry hub, Ambur biryani, scenic Javadi Hills"),
    ("tirupur", "Tirupur", "CJB", 50,
     "Tirupur Bus Stand|Tirupur Railway Station|Avinashi|Palladam|Udumalpet",
     "Coimbatore:coimbatore:50:1|Erode:erode:50:1|Ooty:ooty:105:3|Chennai:chennai:450:7|Palani:palani:85:2",
     "coimbatore|erode|karur|dindigul|nilgiris",
     "Knitwear capital, textile exports hub, Dollar City"),
    ("tiruvannamalai", "Tiruvannamalai", "MAA", 180,
     "Tiruvannamalai Bus Stand|Tiruvannamalai Railway Station|Arunachaleswarar Temple|Ramana Ashram",
     "Chennai:chennai:195:3.5|Vellore:vellore:85:2|Kanchipuram:kanchipuram:90:2|Pondicherry:pondicherry:100:2|Bangalore:bangalore:250:4.5",
     "vellore|ranipet|kanchipuram|villupuram|kallakurichi|dharmapuri",
     "Arunachaleswarar Temple, Girivalam path, Ramana Maharshi Ashram"),
    ("vellore", "Vellore", "MAA", 130,
     "Vellore Bus Stand|Katpadi Junction Railway Station|CMC Hospital|Vellore Fort",
     "Chennai:chennai:140:2.5|Bangalore:bangalore:210:3.5|Tiruvannamalai:tiruvannamalai:85:2|Kanchipuram:kanchipuram:70:1.5|Ranipet:ranipet:25:0.5|Tirupati:tirupati:120:2.5",
     "ranipet|tiruvannamalai|tirupattur|kanchipuram|krishnagiri",
     "CMC Hospital, Vellore Fort, Golden Temple Sripuram, leather exports"),
    ("villupuram", "Villupuram", "MAA", 150,
     "Villupuram Bus Stand|Villupuram Junction Railway Station|Tindivanam|Gingee",
     "Pondicherry:pondicherry:35:0.5|Chennai:chennai:160:3|Cuddalore:cuddalore:35:1|Tiruvannamalai:tiruvannamalai:65:1.5|Kanchipuram:kanchipuram:80:1.5",
     "cuddalore|kanchipuram|tiruvannamalai|kallakurichi|chengalpattu",
     "Gingee Fort, French colonial heritage, ECR coastal route"),
    ("virudhunagar", "Virudhunagar", "IXM", 70,
     "Virudhunagar Bus Stand|Virudhunagar Junction|Sivakasi|Aruppukkottai|Rajapalayam",
     "Madurai:madurai:60:1|Sivakasi:sivakasi:20:0.5|Tirunelveli:tirunelveli:110:2|Thoothukudi:thoothukudi:100:2|Trichy:trichy:190:3.5",
     "madurai|sivagangai|ramanathapuram|thoothukudi|tirunelveli|tenkasi",
     "Fireworks and match capital (Sivakasi), printing hub, Rajapalayam dogs"),
    ("tiruvallur", "Tiruvallur", "MAA", 30,
     "Tiruvallur Bus Stand|Tiruvallur Railway Station|Avadi|Poonamallee|Sriperumbudur",
     "Chennai:chennai:40:1|Kanchipuram:kanchipuram:50:1|Vellore:vellore:100:2|Ranipet:ranipet:80:1.5|Chengalpattu:chengalpattu:60:1.5",
     "chennai|kanchipuram|ranipet|vellore|chengalpattu",
     "Sriperumbudur birthplace of Ramanuja, auto manufacturing hub"),
]

# ─── TAMIL NADU TOWNS ─────────────────────────────────────────────
TN_TOWNS = [
    ("hosur", "Hosur", "BLR", 40,
     "Hosur Bus Stand|Hosur Railway Station|SIPCOT Industrial Area|Hosur IT Park",
     "Bangalore:bangalore:45:1|Krishnagiri:krishnagiri:45:1|Salem:salem:150:2.5|Chennai:chennai:310:5|Dharmapuri:dharmapuri:100:2",
     "krishnagiri|bangalore|dharmapuri|vellore",
     "Gateway to TN from Bangalore, IT hub, SIPCOT industrial area"),
    ("ooty", "Ooty", "CJB", 90,
     "Ooty Bus Stand|Ooty Railway Station|Charring Cross|Botanical Gardens|Lake Area",
     "Coimbatore:coimbatore:90:2.5|Mysore:mysore:130:3|Bangalore:bangalore:280:6|Coonoor:coonoor:20:0.5|Mettupalayam:mettupalayam:50:1.5",
     "coimbatore|mysore|coonoor|mettupalayam|wayanad",
     "Queen of Hill Stations, Nilgiri Mountain Railway, botanical gardens"),
    ("kodaikanal", "Kodaikanal", "IXM", 120,
     "Kodaikanal Bus Stand|Kodai Lake|Coakers Walk|Seven Roads Junction",
     "Madurai:madurai:120:3|Dindigul:dindigul:80:2.5|Trichy:trichy:195:4|Coimbatore:coimbatore:250:5|Palani:palani:65:2",
     "dindigul|theni|madurai|palani",
     "Princess of Hill Stations, Kodai Lake, Silver Cascade, pine forests"),
    ("kumbakonam", "Kumbakonam", "TRZ", 85,
     "Kumbakonam Bus Stand|Kumbakonam Railway Station|Mahamaham Tank|Darasuram",
     "Thanjavur:thanjavur:35:0.5|Trichy:trichy:95:2|Mayiladuthurai:mayiladuthurai:30:0.5|Chennai:chennai:300:5|Nagapattinam:nagapattinam:55:1.5",
     "thanjavur|mayiladuthurai|nagapattinam|ariyalur|trichy",
     "Temple town, Mahamaham tank, Kumbakonam degree coffee, Chola temples"),
    ("nagercoil", "Nagercoil", "TRV", 80,
     "Nagercoil Bus Stand|Nagercoil Junction Railway Station|Kottar|Vadasery",
     "Kanyakumari:kanyakumari:20:0.5|Trivandrum:trivandrum:85:2|Tirunelveli:tirunelveli:75:1.5|Madurai:madurai:240:4.5|Thoothukudi:thoothukudi:160:3",
     "kanyakumari|tirunelveli|tenkasi|trivandrum",
     "Gateway to Kanyakumari, Padmanabhapuram Palace, rubber capital"),
    ("karaikudi", "Karaikudi", "TRZ", 90,
     "Karaikudi Bus Stand|Karaikudi Railway Station|Chettinad Palace|Devakottai",
     "Madurai:madurai:60:1|Trichy:trichy:100:2|Sivagangai:sivagangai:12:0.5|Thanjavur:thanjavur:85:2|Rameshwaram:rameshwaram:120:2.5",
     "sivagangai|madurai|pudukkottai|ramanathapuram",
     "Chettinad heritage, palatial mansions, spicy Chettinad cuisine"),
    ("palani", "Palani", "CJB", 100,
     "Palani Bus Stand|Palani Railway Station|Murugan Temple|Palani Hills",
     "Dindigul:dindigul:25:0.5|Madurai:madurai:100:2|Coimbatore:coimbatore:130:2.5|Kodaikanal:kodaikanal:65:2|Tirupur:tirupur:85:2",
     "dindigul|coimbatore|theni|karur|tirupur",
     "Palani Murugan Temple, one of the six abodes of Lord Murugan"),
    ("sivakasi", "Sivakasi", "IXM", 80,
     "Sivakasi Bus Stand|Sivakasi Town|Virudhunagar Junction",
     "Madurai:madurai:70:1.5|Virudhunagar:virudhunagar:20:0.5|Tirunelveli:tirunelveli:120:2.5|Rajapalayam:rajapalayam:35:0.5|Trichy:trichy:200:3.5",
     "virudhunagar|madurai|thoothukudi|ramanathapuram",
     "Fireworks and match industry capital, mini Japan of India"),
    ("srirangam", "Srirangam", "TRZ", 15,
     "Srirangam Bus Stand|Ranganathaswamy Temple|Srirangam Railway Station",
     "Trichy:trichy:10:0.5|Thanjavur:thanjavur:60:1.5|Madurai:madurai:140:2.5|Kumbakonam:kumbakonam:90:2|Chennai:chennai:330:5",
     "trichy|ariyalur|perambalur|thanjavur",
     "Sri Ranganathaswamy Temple, largest functioning Hindu temple in the world"),
    ("chrompet", "Chrompet", "MAA", 20,
     "Chrompet Bus Stand|Chrompet Railway Station|Pallavaram|Tambaram",
     "Chennai:chennai:22:0.5|Chengalpattu:chengalpattu:30:0.5|Kanchipuram:kanchipuram:45:1|Mahabalipuram:mahabalipuram:45:1|Pondicherry:pondicherry:140:3",
     "chennai|chengalpattu|kanchipuram|tiruvallur",
     "Chennai suburb, railway junction, residential and commercial hub"),
    ("neyveli", "Neyveli", "MAA", 200,
     "Neyveli Bus Stand|Neyveli Township|NLC Gate",
     "Cuddalore:cuddalore:35:0.5|Trichy:trichy:130:2.5|Pondicherry:pondicherry:65:1.5|Chennai:chennai:230:4|Villupuram:villupuram:50:1",
     "cuddalore|villupuram|ariyalur|perambalur",
     "NLC mining township, lignite capital of India, planned township"),
    ("tiruchendur", "Tiruchendur", "IXM", 110,
     "Tiruchendur Bus Stand|Tiruchendur Temple|Tiruchendur Beach",
     "Thoothukudi:thoothukudi:40:1|Tirunelveli:tirunelveli:55:1|Madurai:madurai:190:3|Nagercoil:nagercoil:130:2.5|Rameshwaram:rameshwaram:200:3.5",
     "thoothukudi|tirunelveli|ramanathapuram|kanyakumari",
     "Arulmigu Subramaniya Swamy Temple, seaside Murugan abode"),
    ("chidambaram", "Chidambaram", "MAA", 190,
     "Chidambaram Bus Stand|Annamalai University|Nataraja Temple",
     "Cuddalore:cuddalore:35:0.5|Pondicherry:pondicherry:65:1.5|Trichy:trichy:170:3|Chennai:chennai:230:4|Nagapattinam:nagapattinam:65:1.5",
     "cuddalore|nagapattinam|mayiladuthurai|villupuram",
     "Nataraja Temple with Chidambaram Rahasyam, Annamalai University"),
    ("velankanni", "Velankanni", "TRZ", 120,
     "Velankanni Bus Stand|Velankanni Basilica|Beach Road",
     "Nagapattinam:nagapattinam:12:0.5|Thanjavur:thanjavur:85:2|Trichy:trichy:150:3|Chennai:chennai:320:5.5|Kumbakonam:kumbakonam:60:1.5",
     "nagapattinam|thanjavur|mayiladuthurai|karaikal",
     "Basilica of Our Lady of Good Health, Lourdes of the East"),
    ("pollachi", "Pollachi", "CJB", 40,
     "Pollachi Bus Stand|Pollachi Railway Station|Aliyar Dam|Topslip",
     "Coimbatore:coimbatore:40:1|Palakkad:palakkad:50:1|Palani:palani:75:1.5|Madurai:madurai:200:3.5|Valparai:valparai:65:2",
     "coimbatore|palakkad|dindigul|tirupur|theni",
     "Coconut capital, Aliyar Dam, Topslip wildlife, gateway to Valparai"),
    ("mettupalayam", "Mettupalayam", "CJB", 45,
     "Mettupalayam Bus Stand|Mettupalayam Railway Station|Karamadai",
     "Coimbatore:coimbatore:35:0.5|Ooty:ooty:50:1.5|Coonoor:coonoor:30:1|Erode:erode:100:2|Tirupur:tirupur:75:1.5",
     "coimbatore|nilgiris|erode|tirupur",
     "Gateway to Nilgiris, Nilgiri Mountain Railway starting point"),
    ("coonoor", "Coonoor", "CJB", 75,
     "Coonoor Bus Stand|Coonoor Railway Station|Sims Park|Dolphin Nose",
     "Ooty:ooty:20:0.5|Mettupalayam:mettupalayam:30:1|Coimbatore:coimbatore:65:2|Mysore:mysore:150:3.5|Bangalore:bangalore:290:6",
     "ooty|mettupalayam|coimbatore|mysore",
     "Nilgiri tea estates, Sims Park, Dolphin Nose viewpoint"),
    ("mahabalipuram", "Mahabalipuram", "MAA", 50,
     "Mahabalipuram Bus Stand|Shore Temple|Five Rathas|ECR Junction",
     "Chennai:chennai:55:1.5|Chengalpattu:chengalpattu:30:0.5|Kanchipuram:kanchipuram:55:1|Pondicherry:pondicherry:95:2|Tiruvannamalai:tiruvannamalai:150:3",
     "chengalpattu|chennai|kanchipuram|villupuram",
     "UNESCO Shore Temple, Pallava rock-cut monuments, beach town"),
]

# ─── KERALA DISTRICTS ─────────────────────────────────────────────
KL = "Kerala"
KL_DATA = [
    ("trivandrum", "Thiruvananthapuram", "TRV", 5,
     "Trivandrum Central Railway Station|Thampanoor Bus Stand|East Fort|Technopark|Kovalam",
     "Kanyakumari:kanyakumari:90:2|Kochi:kochi:210:4|Kollam:kollam:70:1.5|Nagercoil:nagercoil:85:2|Madurai:madurai:310:5.5",
     "kollam|kanyakumari|tirunelveli|pathanamthitta",
     "Kerala capital, Padmanabhaswamy Temple, Kovalam Beach, IT hub"),
    ("kollam", "Kollam", "TRV", 65,
     "Kollam Bus Stand|Kollam Junction Railway Station|Ashtamudi Lake|Cashew Junction",
     "Trivandrum:trivandrum:70:1.5|Kochi:kochi:140:3|Alappuzha:alappuzha:85:2|Pathanamthitta:pathanamthitta:60:1.5|Kanyakumari:kanyakumari:145:3",
     "trivandrum|pathanamthitta|alappuzha|tenkasi",
     "Ashtamudi Lake, cashew capital, gateway to Kerala backwaters"),
    ("pathanamthitta", "Pathanamthitta", "TRV", 110,
     "Pathanamthitta Bus Stand|Pathanamthitta Town|Sabarimala Base Camp|Adoor",
     "Kochi:kochi:110:2.5|Trivandrum:trivandrum:130:3|Kollam:kollam:60:1.5|Alappuzha:alappuzha:70:1.5|Kottayam:kottayam:50:1",
     "kollam|alappuzha|kottayam|idukki|trivandrum",
     "Sabarimala Temple, pilgrimage capital of Kerala, river district"),
    ("alappuzha", "Alappuzha", "COK", 55,
     "Alappuzha Bus Stand|Alappuzha Railway Station|Alappuzha Beach|Finishing Point",
     "Kochi:kochi:55:1.5|Kottayam:kottayam:35:1|Trivandrum:trivandrum:155:3|Kollam:kollam:85:2|Kumarakom:kumarakom:30:0.5",
     "kottayam|kollam|pathanamthitta|kochi|idukki",
     "Venice of the East, houseboat backwaters, Nehru Trophy Boat Race"),
    ("kottayam", "Kottayam", "COK", 60,
     "Kottayam Bus Stand|Kottayam Railway Station|Nagampadom|Kumarakom",
     "Kochi:kochi:60:1.5|Alappuzha:alappuzha:35:1|Munnar:munnar:100:3|Thekkady:thekkady:115:3|Kumarakom:kumarakom:15:0.5",
     "alappuzha|idukki|pathanamthitta|ernakulam",
     "Rubber capital of India, Kumarakom backwaters, literary hub"),
    ("idukki", "Idukki", "COK", 120,
     "Idukki Bus Stand|Thodupuzha|Painavu|Adimali",
     "Munnar:munnar:45:1.5|Kochi:kochi:120:3|Thekkady:thekkady:60:2|Kottayam:kottayam:90:2.5|Madurai:madurai:160:4",
     "kottayam|ernakulam|theni|pathanamthitta",
     "Idukki Arch Dam, spice gardens, highest district in Kerala"),
    ("kochi", "Kochi", "COK", 25,
     "Ernakulam Junction Railway Station|Ernakulam Town Railway Station|Vyttila Hub|Fort Kochi|Marine Drive",
     "Trivandrum:trivandrum:210:4|Munnar:munnar:130:4|Alappuzha:alappuzha:55:1.5|Thrissur:thrissur:80:2|Coimbatore:coimbatore:195:4|Thekkady:thekkady:140:4",
     "alappuzha|kottayam|thrissur|idukki|palakkad",
     "Queen of Arabian Sea, Fort Kochi, IT hub, backwater cruise hub"),
    ("thrissur", "Thrissur", "COK", 60,
     "Thrissur Bus Stand|Thrissur Railway Station|Swaraj Round|Vadakkunnathan Temple",
     "Kochi:kochi:80:2|Palakkad:palakkad:55:1|Coimbatore:coimbatore:130:3|Guruvayur:guruvayur:25:0.5|Malappuram:malappuram:80:2",
     "palakkad|kochi|malappuram|idukki",
     "Cultural capital of Kerala, Thrissur Pooram, Vadakkunnathan Temple"),
    ("palakkad", "Palakkad", "COK", 90,
     "Palakkad Bus Stand|Palakkad Junction Railway Station|Palakkad Fort|Olavakkode",
     "Coimbatore:coimbatore:55:1|Thrissur:thrissur:55:1|Pollachi:pollachi:50:1|Kochi:kochi:145:3|Malappuram:malappuram:75:1.5",
     "thrissur|malappuram|coimbatore|kochi",
     "Gateway of Kerala, Palakkad Gap, Silent Valley, rice granary"),
    ("malappuram", "Malappuram", "CCJ", 50,
     "Malappuram Bus Stand|Tirur Railway Station|Manjeri|Perinthalmanna",
     "Kozhikode:kozhikode:50:1|Palakkad:palakkad:75:1.5|Thrissur:thrissur:80:2|Kochi:kochi:160:3|Coimbatore:coimbatore:130:3",
     "kozhikode|palakkad|thrissur|nilambur|wayanad",
     "Historical Malabar region, educational hub, Kottakkunnu heritage"),
    ("kozhikode", "Kozhikode", "CCJ", 25,
     "Kozhikode Railway Station|New Bus Stand|Mananchira|SM Street|Beach Road",
     "Wayanad:wayanad:80:2|Kannur:kannur:90:2|Malappuram:malappuram:50:1|Bangalore:bangalore:340:6|Mysore:mysore:240:4.5|Ooty:ooty:155:3.5",
     "malappuram|wayanad|kannur|nilambur",
     "City of Spices, Kozhikode Beach, Kappad historic landing, halwa"),
    ("wayanad", "Wayanad", "CCJ", 80,
     "Kalpetta Bus Stand|Sultan Bathery|Mananthavady|Meenangadi",
     "Kozhikode:kozhikode:80:2|Mysore:mysore:100:2.5|Bangalore:bangalore:280:5|Kannur:kannur:100:2.5|Ooty:ooty:100:2.5",
     "kozhikode|kannur|mysore|nilgiris|malappuram",
     "Western Ghats paradise, Edakkal Caves, Banasura Dam, spice estates"),
    ("kannur", "Kannur", "KLO", 25,
     "Kannur Railway Station|Kannur Bus Stand|Payyambalam Beach|Fort Area",
     "Kozhikode:kozhikode:90:2|Kasaragod:kasaragod:105:2.5|Wayanad:wayanad:100:2.5|Mangalore:mangalore:145:3|Thalassery:thalassery:22:0.5",
     "kozhikode|kasaragod|wayanad|malappuram",
     "Land of looms and lores, Theyyam art, St Angelo Fort, coir industry"),
    ("kasaragod", "Kasaragod", "IXE", 50,
     "Kasaragod Bus Stand|Kasaragod Railway Station|Bekal Fort|Kanhangad",
     "Mangalore:mangalore:55:1|Kannur:kannur:105:2.5|Kozhikode:kozhikode:195:4|Bangalore:bangalore:370:6.5|Bekal:bekal:15:0.5",
     "kannur|mangalore|kozhikode",
     "Bekal Fort, northernmost district of Kerala, seven languages district"),
]

# ─── KERALA TOWNS ─────────────────────────────────────────────────
KL_TOWNS = [
    ("munnar", "Munnar", "COK", 110,
     "Munnar Bus Stand|Munnar Town|Old Munnar|KDHP Tea Museum",
     "Kochi:kochi:130:4|Thekkady:thekkady:90:3|Madurai:madurai:150:4|Coimbatore:coimbatore:175:4.5|Kottayam:kottayam:100:3",
     "idukki|kochi|theni|kottayam",
     "Tea capital of South India, Eravikulam, Mattupetty Dam, honeymoon spot"),
    ("alleppey", "Alleppey", "COK", 55,
     "Alleppey Bus Stand|Alleppey Railway Station|Alleppey Beach|KSRTC Stand",
     "Kochi:kochi:55:1.5|Kumarakom:kumarakom:25:0.5|Trivandrum:trivandrum:155:3|Kottayam:kottayam:35:1|Kollam:kollam:85:2",
     "alappuzha|kottayam|kochi|kollam",
     "Houseboat paradise, backwater capital, Alappuzha Beach, coir"),
    ("thekkady", "Thekkady", "COK", 130,
     "Thekkady Bus Stand|Kumily Town|Periyar Tiger Reserve Gate",
     "Munnar:munnar:90:3|Kochi:kochi:140:4|Kottayam:kottayam:115:3|Madurai:madurai:140:3.5|Coimbatore:coimbatore:220:5",
     "idukki|kottayam|theni|madurai",
     "Periyar Tiger Reserve, spice plantation tours, elephant rides"),
    ("guruvayur", "Guruvayur", "COK", 70,
     "Guruvayur Bus Stand|Guruvayur Railway Station|Guruvayur Temple",
     "Thrissur:thrissur:25:0.5|Kochi:kochi:80:2|Palakkad:palakkad:75:1.5|Coimbatore:coimbatore:140:3|Kozhikode:kozhikode:140:3",
     "thrissur|palakkad|malappuram|kochi",
     "Guruvayur Sri Krishna Temple, Punnathur Kotta elephant sanctuary"),
    ("kovalam", "Kovalam", "TRV", 15,
     "Kovalam Beach Junction|Lighthouse Beach|Hawa Beach|Samudra Beach",
     "Trivandrum:trivandrum:15:0.5|Kanyakumari:kanyakumari:80:2|Kollam:kollam:80:1.5|Varkala:varkala:50:1|Poovar:poovar:10:0.5",
     "trivandrum|kanyakumari|kollam",
     "Crescent beach, lighthouse beach, Ayurveda hub, international beach resort"),
    ("varkala", "Varkala", "TRV", 40,
     "Varkala Bus Stand|Varkala Railway Station|Varkala Cliff|Papanasam Beach",
     "Trivandrum:trivandrum:50:1|Kollam:kollam:35:0.5|Kochi:kochi:155:3|Alappuzha:alappuzha:110:2.5|Kanyakumari:kanyakumari:120:2.5",
     "trivandrum|kollam|pathanamthitta",
     "Varkala Cliff, Papanasam Beach, Janardanaswamy Temple, coastal retreat"),
    ("kumarakom", "Kumarakom", "COK", 55,
     "Kumarakom Boat Jetty|Kumarakom Bird Sanctuary|Taj Hotel Area",
     "Kottayam:kottayam:15:0.5|Alappuzha:alappuzha:30:0.5|Kochi:kochi:55:1.5|Munnar:munnar:115:3|Thekkady:thekkady:120:3",
     "kottayam|alappuzha|kochi|idukki",
     "Vembanad Lake backwaters, bird sanctuary, luxury houseboats"),
]

# ─── KARNATAKA DISTRICTS ──────────────────────────────────────────
KA = "Karnataka"
KA_DATA = [
    ("bagalkot", "Bagalkot", "HBX", 130,
     "Bagalkot Bus Stand|Bagalkot Railway Station|Badami|Pattadakal",
     "Hubli:hubli:120:2.5|Vijayapura:vijayapura:80:2|Belagavi:belagavi:160:3|Bangalore:bangalore:500:8|Hampi:hampi:140:3",
     "vijayapura|belagavi|gadag|koppal|hubli",
     "Badami Caves, Pattadakal UNESCO site, Aihole cradle of architecture"),
    ("ballari", "Ballari", "HBX", 180,
     "Ballari Bus Stand|Ballari Junction Railway Station|Ballari Fort|Hospet",
     "Hampi:hampi:15:0.5|Hubli:hubli:200:3.5|Bangalore:bangalore:310:5|Hyderabad:hyderabad:370:6|Davangere:davangere:130:2.5",
     "koppal|raichur|vijayanagara|davangere|kalaburagi",
     "Hampi UNESCO site, Vijayanagara Empire ruins, iron ore mining hub"),
    ("belagavi", "Belagavi", "HBX", 130,
     "Belagavi Bus Stand|Belagavi Railway Station|Camp Area|Rani Channamma Circle",
     "Hubli:hubli:100:2|Goa:goa:110:2.5|Mumbai:mumbai:500:8|Pune:pune:380:6|Bangalore:bangalore:500:8|Kolhapur:kolhapur:110:2",
     "bagalkot|dharwad|hubli|uttara-kannada|vijayapura",
     "Second capital of Karnataka, military cantonment, Jain heritage"),
    ("bangalore", "Bangalore", "BLR", 35,
     "Majestic Bus Stand|Bangalore City Railway Station|Whitefield|Electronic City|Koramangala|Hebbal",
     "Chennai:chennai:350:6|Mysore:mysore:150:3|Hyderabad:hyderabad:570:8|Coimbatore:coimbatore:365:6|Hosur:hosur:45:1|Tirupati:tirupati:250:4|Mangalore:mangalore:350:6|Ooty:ooty:280:6",
     "hosur|chikballapur|tumakuru|ramanagara|mandya|kolar",
     "Silicon Valley of India, IT capital, garden city, cosmopolitan hub"),
    ("bidar", "Bidar", "HYD", 140,
     "Bidar Bus Stand|Bidar Railway Station|Bidar Fort|Basavakalyan",
     "Hyderabad:hyderabad:150:3|Kalaburagi:kalaburagi:110:2|Bangalore:bangalore:680:10|Aurangabad:aurangabad:280:5|Solapur:solapur:230:4",
     "kalaburagi|nizamabad|nanded|adilabad",
     "Bidar Fort, Bahmani Sultanate heritage, whispering gallery"),
    ("chamarajanagar", "Chamarajanagar", "BLR", 180,
     "Chamarajanagar Bus Stand|Kollegal|Male Mahadeshwara Hills",
     "Mysore:mysore:60:1.5|Bangalore:bangalore:210:4|Ooty:ooty:130:3|Coimbatore:coimbatore:210:4|Salem:salem:200:3.5",
     "mysore|mandya|ramanagara|nilgiris|erode",
     "Male Mahadeshwara Hills, BR Hills wildlife, Cauvery fishing camp"),
    ("chikballapur", "Chikballapur", "BLR", 40,
     "Chikballapur Bus Stand|Chikballapur Railway Station|Nandi Hills",
     "Bangalore:bangalore:60:1.5|Kolar:kolar:40:1|Tirupati:tirupati:200:3.5|Tumakuru:tumakuru:100:2|Chittoor:chittoor:140:2.5",
     "bangalore|kolar|tumakuru|ramanagara|tirupattur",
     "Nandi Hills sunrise point, granite quarries, silk farming"),
    ("chikkamagaluru", "Chikkamagaluru", "IXE", 180,
     "Chikkamagaluru Bus Stand|Kadur Railway Station|Mullayanagiri|Coffee Estate Area",
     "Bangalore:bangalore:240:4.5|Mangalore:mangalore:150:3|Hassan:hassan:55:1.5|Shimoga:shivamogga:90:2|Mysore:mysore:175:3.5",
     "hassan|shivamogga|udupi|davangere|tumakuru",
     "Coffee land of India, Mullayanagiri peak, Baba Budangiri, trekking hub"),
    ("chitradurga", "Chitradurga", "HBX", 150,
     "Chitradurga Bus Stand|Chitradurga Fort|Challakere|Holalkere",
     "Davangere:davangere:60:1.5|Bangalore:bangalore:200:3.5|Hubli:hubli:180:3|Shimoga:shivamogga:110:2|Tumakuru:tumakuru:120:2",
     "davangere|tumakuru|ballari|shivamogga|haveri",
     "Stone Fortress, Chandravalli caves, Onake Obavva warrior heritage"),
    ("davangere", "Davangere", "HBX", 120,
     "Davangere Bus Stand|Davangere Railway Station|Benne Dosa Area",
     "Bangalore:bangalore:260:4.5|Hubli:hubli:130:2.5|Shimoga:shivamogga:100:2|Chitradurga:chitradurga:60:1.5|Bellary:ballari:130:2.5",
     "chitradurga|haveri|shivamogga|ballari|gadag",
     "Benne Dosa capital, cotton textile hub, education center"),
    ("dharwad", "Dharwad", "HBX", 15,
     "Dharwad Bus Stand|Dharwad Railway Station|Karnataka University|Saptapur",
     "Hubli:hubli:20:0.5|Belagavi:belagavi:80:2|Bangalore:bangalore:420:7|Goa:goa:160:3|Bagalkot:bagalkot:95:2",
     "hubli|belagavi|haveri|gadag|bagalkot|uttara-kannada",
     "Dharwad Pedha sweet, education hub, Hindustani classical music center"),
    ("gadag", "Gadag", "HBX", 60,
     "Gadag Bus Stand|Gadag Railway Station|Lakkundi|Ron",
     "Hubli:hubli:60:1.5|Davangere:davangere:100:2|Bagalkot:bagalkot:90:2|Hampi:hampi:110:2|Bangalore:bangalore:430:7",
     "dharwad|haveri|koppal|bagalkot|ballari",
     "Lakkundi Jain temples, Trikuteshwara temple, cotton trading center"),
    ("hassan", "Hassan", "BLR", 160,
     "Hassan Bus Stand|Hassan Railway Station|Belur|Halebid",
     "Bangalore:bangalore:185:3.5|Mysore:mysore:115:2.5|Mangalore:mangalore:170:3.5|Shimoga:shivamogga:100:2|Chikkamagaluru:chikkamagaluru:55:1.5",
     "mysore|chikkamagaluru|mandya|tumakuru|shivamogga",
     "Belur-Halebid Hoysala temples, Shravanabelagola Bahubali statue"),
    ("haveri", "Haveri", "HBX", 80,
     "Haveri Bus Stand|Haveri Railway Station|Ranebennur|Byadgi",
     "Hubli:hubli:70:1.5|Davangere:davangere:75:1.5|Shimoga:shivamogga:90:2|Bangalore:bangalore:350:6|Belagavi:belagavi:150:3",
     "dharwad|davangere|shivamogga|gadag|chitradurga",
     "Byadgi chilli market, handloom textiles, Ranebennur blackbuck sanctuary"),
    ("kalaburagi", "Kalaburagi", "HYD", 220,
     "Kalaburagi Bus Stand|Kalaburagi Railway Station|Gulbarga Fort|Sharana Basaveshwara Temple",
     "Hyderabad:hyderabad:220:4|Bidar:bidar:110:2|Solapur:solapur:110:2|Bangalore:bangalore:620:9|Raichur:raichur:130:2.5",
     "bidar|raichur|yadgir|vijayapura",
     "Gulbarga Fort, Sharana Basaveshwara Temple, Al-Beruni heritage"),
    ("kolar", "Kolar", "BLR", 55,
     "Kolar Bus Stand|Kolar Railway Station|KGF|Bangarpet",
     "Bangalore:bangalore:65:1.5|Chikballapur:chikballapur:40:1|Tirupati:tirupati:170:3|Chennai:chennai:280:5|Vellore:vellore:150:2.5",
     "bangalore|chikballapur|tumakuru|chittoor|tiruvannamalai",
     "Kolar Gold Fields, Anthargange caves, Kolaramma Temple"),
    ("koppal", "Koppal", "HBX", 130,
     "Koppal Bus Stand|Koppal Railway Station|Kuknur|Gangavathi",
     "Hampi:hampi:25:0.5|Hubli:hubli:140:2.5|Ballari:ballari:50:1|Raichur:raichur:80:2|Bangalore:bangalore:360:6",
     "ballari|raichur|gadag|bagalkot|vijayanagara",
     "Gateway to Hampi, Anjanadri Hill (Hanuman birthplace), Tungabhadra Dam"),
    ("mandya", "Mandya", "BLR", 100,
     "Mandya Bus Stand|Mandya Railway Station|Srirangapatna|KRS Dam",
     "Mysore:mysore:45:1|Bangalore:bangalore:100:2|Hassan:hassan:90:2|Coimbatore:coimbatore:260:4.5|Madurai:madurai:360:6",
     "mysore|bangalore|hassan|ramanagara|chamarajanagar",
     "Sugar capital of Karnataka, KRS Dam, Srirangapatna Tipu heritage"),
    ("mysore", "Mysore", "BLR", 165,
     "Mysore Bus Stand|Mysore Junction Railway Station|Chamundi Hills|Sayyaji Rao Road",
     "Bangalore:bangalore:150:3|Ooty:ooty:130:3|Coorg:coorg:115:2.5|Hassan:hassan:115:2.5|Mangalore:mangalore:240:5|Wayanad:wayanad:150:3",
     "mandya|chamarajanagar|hassan|ramanagara|coorg",
     "City of Palaces, Mysore Palace, Chamundi Hills, Dasara festival"),
    ("raichur", "Raichur", "HYD", 260,
     "Raichur Bus Stand|Raichur Junction Railway Station|Raichur Fort",
     "Hyderabad:hyderabad:300:5|Kalaburagi:kalaburagi:130:2.5|Ballari:ballari:105:2|Bangalore:bangalore:410:7|Hubli:hubli:250:4",
     "kalaburagi|yadgir|ballari|koppal|vijayapura",
     "Raichur Fort, rice and cotton granary, Narayanpur Dam"),
    ("ramanagara", "Ramanagara", "BLR", 45,
     "Ramanagara Bus Stand|Ramanagara Railway Station|Channapatna|Sholay Rocks",
     "Bangalore:bangalore:55:1|Mysore:mysore:95:2|Mandya:mandya:50:1|Hassan:hassan:130:2.5|Tumakuru:tumakuru:80:2",
     "bangalore|mandya|tumakuru|mysore|chamarajanagar",
     "Sholay filming location, silk town Channapatna, rock climbing hub"),
    ("shivamogga", "Shivamogga", "HBX", 130,
     "Shivamogga Bus Stand|Shivamogga Railway Station|Bhadravathi|Jog Falls Road",
     "Bangalore:bangalore:280:5|Mangalore:mangalore:170:3.5|Hubli:hubli:150:3|Hassan:hassan:100:2|Davangere:davangere:100:2",
     "chikkamagaluru|hassan|haveri|davangere|uttara-kannada",
     "Gateway to Jog Falls, Sharavathi Valley, Western Ghats greenery"),
    ("tumakuru", "Tumakuru", "BLR", 60,
     "Tumakuru Bus Stand|Tumakuru Railway Station|Sira|Gubbi",
     "Bangalore:bangalore:70:1.5|Hassan:hassan:130:2.5|Chitradurga:chitradurga:120:2|Davangere:davangere:195:3.5|Mysore:mysore:175:3",
     "bangalore|chitradurga|hassan|mandya|ramanagara|chikballapur",
     "Coconut capital, Siddaganga Mutt, Devarayanadurga hills"),
    ("udupi", "Udupi", "IXE", 55,
     "Udupi Bus Stand|Udupi Railway Station|Sri Krishna Matha|Malpe Beach",
     "Mangalore:mangalore:60:1.5|Shimoga:shivamogga:140:3|Bangalore:bangalore:400:7|Hubli:hubli:260:5|Murudeshwar:murudeshwar:80:2",
     "mangalore|shivamogga|uttara-kannada|chikkamagaluru",
     "Udupi Sri Krishna Temple, Malpe Beach, Manipal university town"),
    ("uttara-kannada", "Uttara Kannada", "HBX", 180,
     "Karwar Bus Stand|Sirsi Bus Stand|Dandeli|Gokarna|Kumta",
     "Goa:goa:60:1.5|Hubli:hubli:120:2.5|Mangalore:mangalore:230:4.5|Bangalore:bangalore:480:8|Shimoga:shivamogga:160:3",
     "belagavi|dharwad|haveri|shivamogga|udupi",
     "Gokarna beaches, Dandeli adventure sports, Jog Falls, coastal Karnataka"),
    ("vijayanagara", "Vijayanagara", "HBX", 160,
     "Hosapete Bus Stand|Hosapete Railway Station|Hampi Bazaar|Tungabhadra Dam",
     "Hubli:hubli:165:3|Ballari:ballari:65:1.5|Bangalore:bangalore:340:5.5|Davangere:davangere:120:2.5|Koppal:koppal:30:0.5",
     "ballari|koppal|raichur|davangere|gadag",
     "Hampi World Heritage Site, Vijayanagara Empire capital ruins"),
    ("vijayapura", "Vijayapura", "HBX", 200,
     "Vijayapura Bus Stand|Vijayapura Railway Station|Gol Gumbaz|Ibrahim Roza",
     "Hubli:hubli:180:3|Solapur:solapur:100:2|Hyderabad:hyderabad:370:6|Belagavi:belagavi:200:3.5|Bangalore:bangalore:530:8",
     "bagalkot|belagavi|kalaburagi|raichur",
     "Gol Gumbaz, Ibrahim Roza, Adil Shahi architecture, grape wines"),
    ("yadgir", "Yadgir", "HYD", 250,
     "Yadgir Bus Stand|Yadgir Railway Station|Yadgir Fort|Sannati",
     "Kalaburagi:kalaburagi:70:1.5|Raichur:raichur:60:1.5|Hyderabad:hyderabad:250:4.5|Bangalore:bangalore:480:8|Bidar:bidar:170:3",
     "kalaburagi|raichur|ballari|bidar",
     "Yadgir Fort, Sannati Buddhist site, Bhima River heritage"),
]

# ─── KARNATAKA TOWNS ──────────────────────────────────────────────
KA_TOWNS = [
    ("mangalore", "Mangalore", "IXE", 10,
     "Mangalore Central Railway Station|KSRTC Bus Stand|Hampankatta|Bejai|Kankanady",
     "Bangalore:bangalore:350:6|Mysore:mysore:240:5|Coorg:coorg:140:3|Kasaragod:kasaragod:55:1|Udupi:udupi:60:1.5|Goa:goa:360:6",
     "udupi|kasaragod|chikkamagaluru|hassan|coorg",
     "Port city, Mangalorean cuisine, Kudroli Temple, New Mangalore Port"),
    ("hubli", "Hubli", "HBX", 5,
     "Hubli Railway Station|Hubli Bus Stand|Deshpande Nagar|Gokul Road|Vidyanagar",
     "Bangalore:bangalore:400:7|Dharwad:dharwad:20:0.5|Belagavi:belagavi:100:2|Goa:goa:160:3|Hampi:hampi:165:3|Mangalore:mangalore:280:5",
     "dharwad|gadag|haveri|belagavi|uttara-kannada",
     "Commercial capital of North Karnataka, railway junction, trade hub"),
    ("coorg", "Coorg", "IXE", 130,
     "Madikeri Bus Stand|Kushalnagar|Virajpet|Gonikoppal|Somwarpet",
     "Mysore:mysore:115:2.5|Bangalore:bangalore:260:5|Mangalore:mangalore:140:3|Hassan:hassan:120:2.5|Wayanad:wayanad:110:2.5",
     "mysore|hassan|mangalore|wayanad|chamarajanagar",
     "Scotland of India, coffee plantations, Abbey Falls, Dubare elephant camp"),
    ("hampi", "Hampi", "HBX", 170,
     "Hampi Bus Stand|Hampi Bazaar|Virupaksha Temple Gate|Hippie Island",
     "Hosapete:vijayanagara:13:0.5|Hubli:hubli:165:3|Bangalore:bangalore:340:5.5|Goa:goa:310:6|Badami:bagalkot:140:3",
     "vijayanagara|ballari|koppal",
     "UNESCO World Heritage ruins, boulder landscape, backpacker paradise"),
]

# ─── ANDHRA PRADESH DISTRICTS ─────────────────────────────────────
AP = "Andhra Pradesh"
AP_DATA = [
    ("anantapur", "Anantapur", "BLR", 250,
     "Anantapur Bus Stand|Anantapur Railway Station|Penukonda|Dharmavaram",
     "Bangalore:bangalore:260:4.5|Hyderabad:hyderabad:350:5.5|Kurnool:kurnool:130:2.5|Tirupati:tirupati:300:5|Kadapa:kadapa:180:3",
     "kurnool|kadapa|ballari|chittoor|nandyal",
     "Penukonda fort, Lepakshi temple, driest district in AP, peanut capital"),
    ("chittoor", "Chittoor", "TIR", 60,
     "Chittoor Bus Stand|Chittoor Railway Station|Tirupati Road|Kuppam",
     "Tirupati:tirupati:65:1.5|Bangalore:bangalore:170:3|Chennai:chennai:250:4|Vellore:vellore:100:2|Kadapa:kadapa:170:3",
     "tirupati|vellore|kolar|bangalore|annamayya",
     "Horsley Hills, mango orchards, gateway to Tirupati"),
    ("east-godavari", "East Godavari", "VTZ", 170,
     "Rajahmundry Bus Stand|Kakinada Bus Stand|Rajamahendravaram Railway Station",
     "Rajahmundry:rajahmundry:10:0.5|Vizag:vizag:190:3.5|Vijayawada:vijayawada:200:3.5|Kakinada:kakinada:50:1|Hyderabad:hyderabad:500:8",
     "west-godavari|vizag|kakinada|konaseema|anakapalli",
     "Godavari River delta, coconut groves, Rajahmundry, Papikondalu"),
    ("guntur", "Guntur", "VGA", 30,
     "Guntur Bus Stand|Guntur Junction Railway Station|Brodipet|Arundelpet",
     "Vijayawada:vijayawada:30:0.5|Hyderabad:hyderabad:280:5|Amaravati:amaravati:25:0.5|Chennai:chennai:440:7|Bangalore:bangalore:460:7",
     "vijayawada|bapatla|palnadu|ntr|prakasam",
     "Chilli capital of India, Amaravati Buddhist stupa, Kondaveedu Fort"),
    ("kadapa", "Kadapa", "CDP", 15,
     "Kadapa Bus Stand|Kadapa Railway Station|Rajampet|Proddatur",
     "Tirupati:tirupati:130:2.5|Bangalore:bangalore:280:5|Hyderabad:hyderabad:380:6|Kurnool:kurnool:180:3|Anantapur:anantapur:180:3",
     "anantapur|kurnool|chittoor|nandyal|annamayya",
     "Ameen Peer Dargah, Gandikota Grand Canyon, Belum Caves nearby"),
    ("krishna", "Krishna", "VGA", 10,
     "Machilipatnam Bus Stand|Machilipatnam Railway Station|Gudivada|Nuzvid",
     "Vijayawada:vijayawada:65:1.5|Guntur:guntur:90:2|Hyderabad:hyderabad:300:5|Rajahmundry:rajahmundry:175:3|Chennai:chennai:430:7",
     "vijayawada|guntur|west-godavari|ntr|bapatla",
     "Machilipatnam Kalamkari art, ancient port city, Krishna River delta"),
    ("kurnool", "Kurnool", "HYD", 200,
     "Kurnool Bus Stand|Kurnool Railway Station|Nandyal Road|Adoni",
     "Hyderabad:hyderabad:215:4|Bangalore:bangalore:380:6|Anantapur:anantapur:130:2.5|Kadapa:kadapa:180:3|Vijayawada:vijayawada:250:4.5",
     "nandyal|anantapur|kadapa|mahabubnagar|prakasam",
     "Belum Caves, Srisailam temple, former capital of Andhra, Mantralayam"),
    ("nellore", "Nellore", "TIR", 110,
     "Nellore Bus Stand|Nellore Railway Station|Grand Trunk Road|Kavali",
     "Chennai:chennai:180:3|Tirupati:tirupati:130:2.5|Vijayawada:vijayawada:250:4|Hyderabad:hyderabad:420:7|Bangalore:bangalore:380:6",
     "chittoor|tirupati|prakasam|kadapa",
     "Pulicat Lake, Mypadu Beach, aquaculture hub, Udayagiri Fort"),
    ("prakasam", "Prakasam", "VGA", 120,
     "Ongole Bus Stand|Ongole Railway Station|Markapuram|Chirala",
     "Vijayawada:vijayawada:160:3|Hyderabad:hyderabad:350:6|Chennai:chennai:350:6|Guntur:guntur:100:2|Nellore:nellore:130:2.5",
     "guntur|nellore|kurnool|nandyal|bapatla",
     "Ongole cattle breed, Chirala handlooms, Kothapatnam Beach"),
    ("srikakulam", "Srikakulam", "VTZ", 110,
     "Srikakulam Bus Stand|Srikakulam Road Railway Station|Palasa|Amadalavalasa",
     "Vizag:vizag:110:2.5|Hyderabad:hyderabad:630:10|Rajahmundry:rajahmundry:300:5|Brahmapur:brahmapur:90:2",
     "vizianagaram|vizag|parvathipuram-manyam",
     "Arasavalli Sun Temple, Srikurmam temple, northernmost AP district"),
    ("vizag", "Visakhapatnam", "VTZ", 10,
     "Visakhapatnam Railway Station|RTC Complex Bus Stand|Jagadamba Junction|Gajuwaka|MVP Colony",
     "Hyderabad:hyderabad:620:9|Vijayawada:vijayawada:350:5.5|Rajahmundry:rajahmundry:190:3.5|Araku:araku:115:3|Srikakulam:srikakulam:110:2.5",
     "anakapalli|vizianagaram|srikakulam|alluri-sitharama-raju",
     "City of Destiny, Araku Valley, submarine museum, RK Beach, IT hub"),
    ("vizianagaram", "Vizianagaram", "VTZ", 50,
     "Vizianagaram Bus Stand|Vizianagaram Railway Station|Fort Area|Nellimarla",
     "Vizag:vizag:55:1|Srikakulam:srikakulam:55:1|Hyderabad:hyderabad:590:9|Rajahmundry:rajahmundry:250:4.5|Araku:araku:100:2.5",
     "vizag|srikakulam|parvathipuram-manyam|alluri-sitharama-raju",
     "Vizianagaram Fort, Bobbili veena, cultural heritage of North Andhra"),
    ("west-godavari", "West Godavari", "VGA", 170,
     "Eluru Bus Stand|Bhimavaram Bus Stand|Tanuku|Tadepalligudem",
     "Vijayawada:vijayawada:65:1.5|Rajahmundry:rajahmundry:80:2|Hyderabad:hyderabad:350:6|Vizag:vizag:290:5|Chennai:chennai:520:8",
     "east-godavari|krishna|ntr|eluru|konaseema",
     "Kolleru Lake, Bhimavaram prawn farming, Dwarka Tirumala temple"),
    ("alluri-sitharama-raju", "Alluri Sitharama Raju", "VTZ", 130,
     "Paderu Bus Stand|Araku Valley|Lambasingi",
     "Vizag:vizag:115:3|Rajahmundry:rajahmundry:260:5|Hyderabad:hyderabad:640:10|Srikakulam:srikakulam:200:4",
     "vizag|vizianagaram|east-godavari|anakapalli",
     "Araku Valley coffee, Lambasingi (Andhra Kashmir), tribal heritage"),
    ("anakapalli", "Anakapalli", "VTZ", 30,
     "Anakapalli Bus Stand|Anakapalli Railway Station|Yellamanchili|Narsipatnam",
     "Vizag:vizag:30:0.5|Rajahmundry:rajahmundry:200:3.5|Vijayawada:vijayawada:330:5.5|Araku:araku:100:2.5|Kakinada:kakinada:120:2.5",
     "vizag|alluri-sitharama-raju|east-godavari|vizianagaram",
     "Anakapalli jaggery, Bojjannakonda Buddhist heritage, coastal town"),
    ("bapatla", "Bapatla", "VGA", 60,
     "Bapatla Bus Stand|Bapatla Railway Station|Chirala|Addanki",
     "Vijayawada:vijayawada:90:2|Guntur:guntur:55:1|Ongole:ongole:85:2|Hyderabad:hyderabad:320:5.5|Chennai:chennai:380:6",
     "guntur|prakasam|krishna|ntr|palnadu",
     "Bapatla Agricultural College, Chirala handlooms, coastal heritage"),
    ("eluru", "Eluru", "VGA", 130,
     "Eluru Bus Stand|Eluru Railway Station|Dwaraka Tirumala",
     "Vijayawada:vijayawada:65:1.5|Rajahmundry:rajahmundry:100:2|Hyderabad:hyderabad:330:5.5|Guntur:guntur:95:2|Kakinada:kakinada:120:2.5",
     "west-godavari|krishna|ntr|konaseema|east-godavari",
     "Eluru carpets, Dwaraka Tirumala temple, Kolleru Lake"),
    ("kakinada", "Kakinada", "VGA", 170,
     "Kakinada Bus Stand|Samalkot Junction|Kakinada Port|Hope Island",
     "Rajahmundry:rajahmundry:60:1.5|Vizag:vizag:170:3|Vijayawada:vijayawada:200:3.5|Hyderabad:hyderabad:480:8|Chennai:chennai:580:9",
     "east-godavari|konaseema|west-godavari|anakapalli",
     "Port city, Hope Island, Coringa mangroves, natural gas hub"),
    ("konaseema", "Konaseema", "VGA", 180,
     "Amalapuram Bus Stand|Amalapuram Town|Razole|Kothapeta",
     "Rajahmundry:rajahmundry:70:1.5|Kakinada:kakinada:40:1|Vijayawada:vijayawada:200:3.5|Vizag:vizag:200:4|Hyderabad:hyderabad:500:8",
     "east-godavari|kakinada|west-godavari",
     "Godavari delta island, coconut groves, Antarvedi temple"),
    ("ntr", "NTR District", "VGA", 10,
     "Vijayawada Bus Stand|Jaggayyapeta|Nandigama|Tiruvuru",
     "Vijayawada:vijayawada:5:0.2|Hyderabad:hyderabad:275:5|Guntur:guntur:35:0.5|Eluru:eluru:60:1.5|Amaravati:amaravati:30:0.5",
     "vijayawada|guntur|krishna|west-godavari|palnadu",
     "Named after NT Rama Rao, Vijayawada adjacent, Kondapalli toys"),
    ("palnadu", "Palnadu", "VGA", 90,
     "Narasaraopet Bus Stand|Macherla|Gurazala|Piduguralla",
     "Vijayawada:vijayawada:100:2|Guntur:guntur:55:1|Hyderabad:hyderabad:240:4|Kurnool:kurnool:170:3|Amaravati:amaravati:70:1.5",
     "guntur|ntr|kurnool|nandyal|prakasam",
     "Historic Palnadu region, Kotappakonda temple, limestone quarries"),
    ("parvathipuram-manyam", "Parvathipuram Manyam", "VTZ", 130,
     "Parvathipuram Bus Stand|Palakonda|Saluru|Bobbili",
     "Vizag:vizag:140:3|Srikakulam:srikakulam:50:1|Vizianagaram:vizianagaram:60:1.5|Hyderabad:hyderabad:600:9",
     "srikakulam|vizianagaram|alluri-sitharama-raju|vizag",
     "Tribal heritage, Eastern Ghats forests, Bobbili Fort"),
    ("sri-sathya-sai", "Sri Sathya Sai", "BLR", 200,
     "Puttaparthi Bus Stand|Puttaparthi Railway Station|Prasanthi Nilayam",
     "Bangalore:bangalore:200:3.5|Anantapur:anantapur:80:1.5|Hyderabad:hyderabad:390:6|Kadapa:kadapa:170:3|Kurnool:kurnool:160:3",
     "anantapur|kadapa|kurnool|ballari",
     "Puttaparthi Prasanthi Nilayam, Sathya Sai Baba ashram, pilgrimage center"),
    ("nandyal", "Nandyal", "HYD", 210,
     "Nandyal Bus Stand|Nandyal Railway Station|Banaganapalle|Atmakur",
     "Kurnool:kurnool:50:1|Hyderabad:hyderabad:290:5|Vijayawada:vijayawada:250:4.5|Kadapa:kadapa:130:2.5|Bangalore:bangalore:400:7",
     "kurnool|kadapa|prakasam|anantapur|palnadu",
     "Mahanandi temple, Srisailam Dam gateway, Banaganapalle mangoes"),
    ("tirupati", "Tirupati", "TIR", 15,
     "Tirupati Bus Stand|Tirupati Railway Station|Tirumala|Alipiri Footpath Start",
     "Chennai:chennai:135:3|Bangalore:bangalore:250:4|Vellore:vellore:120:2.5|Nellore:nellore:130:2.5|Kadapa:kadapa:130:2.5|Chittoor:chittoor:65:1.5",
     "chittoor|nellore|annamayya|kadapa|vellore",
     "Sri Venkateswara Temple Tirumala, most visited pilgrimage in the world"),
    ("annamayya", "Annamayya", "TIR", 50,
     "Rajampet Bus Stand|Rajampet Railway Station|Kodur|Railway Kodur",
     "Tirupati:tirupati:80:1.5|Kadapa:kadapa:55:1|Chennai:chennai:230:4|Bangalore:bangalore:280:5|Nellore:nellore:170:3",
     "tirupati|kadapa|chittoor|nellore|nandyal",
     "Talakona Waterfalls, Annamayya birthplace, Sri Venkateswara wildlife"),
]

# ─── ANDHRA PRADESH TOWNS ─────────────────────────────────────────
AP_TOWNS = [
    ("vijayawada", "Vijayawada", "VGA", 20,
     "Vijayawada Junction Railway Station|Pandit Nehru Bus Station|Benz Circle|MG Road|Kanaka Durga Temple",
     "Hyderabad:hyderabad:275:5|Guntur:guntur:30:0.5|Chennai:chennai:430:7|Bangalore:bangalore:480:7.5|Rajahmundry:rajahmundry:200:3.5|Tirupati:tirupati:310:5|Vizag:vizag:350:5.5",
     "guntur|krishna|ntr|west-godavari|eluru",
     "Kanaka Durga Temple, Prakasam Barrage, business hub of AP"),
    ("rajahmundry", "Rajahmundry", "RJA", 8,
     "Rajahmundry Railway Station|RTC Complex|Godavari Bridge|Pushkar Ghat",
     "Vijayawada:vijayawada:200:3.5|Vizag:vizag:190:3.5|Kakinada:kakinada:60:1.5|Hyderabad:hyderabad:480:8|Eluru:eluru:100:2",
     "east-godavari|west-godavari|kakinada|konaseema",
     "Godavari River, Pushkaram, Papikondalu boat ride, cultural capital"),
    ("ongole", "Ongole", "VGA", 150,
     "Ongole Bus Stand|Ongole Railway Station|Kurnool Road|Addanki Road",
     "Vijayawada:vijayawada:160:3|Hyderabad:hyderabad:350:6|Chennai:chennai:350:6|Guntur:guntur:100:2|Nellore:nellore:130:2.5",
     "prakasam|guntur|nellore|kurnool|nandyal",
     "Ongole bull breed, Kothapatnam Beach, tobacco trading hub"),
]

# ─── TELANGANA DISTRICTS ──────────────────────────────────────────
TS = "Telangana"
TS_DATA = [
    ("adilabad", "Adilabad", "HYD", 300,
     "Adilabad Bus Stand|Adilabad Railway Station|Nirmal Road|Utnoor",
     "Hyderabad:hyderabad:310:5.5|Nirmal:nirmal:40:1|Mancherial:mancherial:80:1.5|Nagpur:nagpur:280:5|Nizamabad:nizamabad:150:3",
     "nirmal|mancherial|kumuram-bheem-asifabad|nizamabad",
     "Kuntala Waterfall, Kawal Tiger Reserve, tribal heritage"),
    ("bhadradri-kothagudem", "Bhadradri Kothagudem", "HYD", 300,
     "Kothagudem Bus Stand|Bhadrachalam Bus Stand|Bhadrachalam Temple|Manuguru",
     "Hyderabad:hyderabad:310:5.5|Khammam:khammam:80:1.5|Vijayawada:vijayawada:250:4.5|Warangal:warangal:180:3|Rajahmundry:rajahmundry:180:3",
     "khammam|warangal|mulugu|mahabubabad",
     "Bhadrachalam Temple, Godavari River, Kinnerasani wildlife"),
    ("hanumakonda", "Hanumakonda", "HYD", 150,
     "Hanumakonda Bus Stand|Kazipet Junction Railway Station|Warangal Fort Area",
     "Hyderabad:hyderabad:150:3|Warangal:warangal:12:0.5|Karimnagar:karimnagar:70:1.5|Khammam:khammam:110:2|Vijayawada:vijayawada:230:4",
     "warangal|karimnagar|jangaon|mahabubabad|mulugu",
     "Thousand Pillar Temple, Warangal Fort, Kakatiya heritage"),
    ("hyderabad", "Hyderabad", "HYD", 25,
     "Secunderabad Railway Station|Hyderabad Deccan Station|MGBS Bus Stand|JBS Bus Stand|Gachibowli|HITEC City",
     "Bangalore:bangalore:570:8|Vijayawada:vijayawada:275:5|Warangal:warangal:150:3|Tirupati:tirupati:550:8|Chennai:chennai:630:9|Nagpur:nagpur:500:8",
     "rangareddy|medchal-malkajgiri|sangareddy|siddipet|secunderabad",
     "City of Pearls, Charminar, Golconda Fort, HITEC City IT hub"),
    ("jagtial", "Jagtial", "HYD", 175,
     "Jagtial Bus Stand|Jagtial Town|Dharmapuri|Koratla",
     "Karimnagar:karimnagar:35:0.5|Hyderabad:hyderabad:180:3|Nizamabad:nizamabad:80:2|Mancherial:mancherial:75:1.5|Warangal:warangal:100:2",
     "karimnagar|peddapalli|nirmal|nizamabad|rajanna-sircilla",
     "Jagtial Fort, jute industry, Dharmapuri Laxmi Narasimha Temple"),
    ("jangaon", "Jangaon", "HYD", 100,
     "Jangaon Bus Stand|Jangaon Railway Station|Station Ghanpur",
     "Hyderabad:hyderabad:100:2|Warangal:warangal:50:1|Siddipet:siddipet:65:1.5|Nalgonda:nalgonda:100:2|Karimnagar:karimnagar:110:2",
     "warangal|siddipet|nalgonda|suryapet|yadadri-bhuvanagiri",
     "Station Ghanpur temple, handloom weaving, Kakatiya era heritage"),
    ("jayashankar-bhupalpally", "Jayashankar Bhupalpally", "HYD", 250,
     "Bhupalpally Bus Stand|Mahadevpur|Kataram|Tekumatla",
     "Warangal:warangal:100:2|Karimnagar:karimnagar:90:2|Hyderabad:hyderabad:270:5|Mancherial:mancherial:100:2|Khammam:khammam:150:3",
     "mulugu|warangal|karimnagar|mancherial|peddapalli",
     "Dense forests, tribal areas, Laknavaram Lake, scenic Eastern Ghats"),
    ("jogulamba-gadwal", "Jogulamba Gadwal", "HYD", 200,
     "Gadwal Bus Stand|Gadwal Railway Station|Alampur|Ieeja",
     "Hyderabad:hyderabad:210:4|Kurnool:kurnool:80:1.5|Mahabubnagar:mahabubnagar:100:2|Raichur:raichur:55:1|Wanaparthy:wanaparthy:60:1.5",
     "mahabubnagar|wanaparthy|nagarkurnool|narayanpet|raichur",
     "Jogulamba Temple (Shakti Peetha), Alampur Navabrahma temples"),
    ("kamareddy", "Kamareddy", "HYD", 170,
     "Kamareddy Bus Stand|Kamareddy Railway Station|Banswada|Yellareddy",
     "Hyderabad:hyderabad:170:3|Nizamabad:nizamabad:35:0.5|Karimnagar:karimnagar:100:2|Sangareddy:sangareddy:100:2|Medak:medak:85:2",
     "nizamabad|medak|sangareddy|siddipet|rajanna-sircilla",
     "Turmeric markets, Elgandal Fort nearby, agricultural town"),
    ("karimnagar", "Karimnagar", "HYD", 150,
     "Karimnagar Bus Stand|Karimnagar Town|Elgandal Fort|Jagtial Road",
     "Hyderabad:hyderabad:165:3|Warangal:warangal:70:1.5|Nizamabad:nizamabad:110:2|Jagtial:jagtial:35:0.5|Siddipet:siddipet:80:2",
     "jagtial|peddapalli|rajanna-sircilla|siddipet|nizamabad",
     "Silver filigree work, Elgandal Fort, granite exports, education hub"),
    ("khammam", "Khammam", "HYD", 230,
     "Khammam Bus Stand|Khammam Railway Station|Wyra|Kothagudem Road",
     "Hyderabad:hyderabad:195:3.5|Vijayawada:vijayawada:175:3|Warangal:warangal:110:2|Suryapet:suryapet:110:2|Bhadrachalam:bhadradri-kothagudem:100:2",
     "bhadradri-kothagudem|suryapet|nalgonda|warangal|mahabubabad",
     "Khammam Fort, paddy granary, tribal areas, Kinnerasani Dam"),
    ("kumuram-bheem-asifabad", "Kumuram Bheem Asifabad", "HYD", 330,
     "Asifabad Bus Stand|Kerameri|Kaghaznagar|Wankidi",
     "Adilabad:adilabad:60:1.5|Mancherial:mancherial:80:2|Nirmal:nirmal:80:2|Hyderabad:hyderabad:340:6|Nagpur:nagpur:200:4",
     "adilabad|mancherial|nirmal",
     "Tribal heritage, Kumuram Bheem freedom fighter, Jodeghat memorial"),
    ("mahabubabad", "Mahabubabad", "HYD", 200,
     "Mahabubabad Bus Stand|Mahabubabad Town|Thorrur|Kesamudram",
     "Warangal:warangal:60:1.5|Khammam:khammam:80:2|Hyderabad:hyderabad:200:4|Karimnagar:karimnagar:110:2|Bhadrachalam:bhadradri-kothagudem:130:2.5",
     "warangal|khammam|mulugu|bhadradri-kothagudem|jangaon",
     "Tribal district, Laknavaram Lake, Tadvai wildlife, bamboo craft"),
    ("mahabubnagar", "Mahabubnagar", "HYD", 100,
     "Mahabubnagar Bus Stand|Mahabubnagar Railway Station|Jadcherla|Narayanpet Road",
     "Hyderabad:hyderabad:100:2|Kurnool:kurnool:200:3.5|Raichur:raichur:200:3.5|Wanaparthy:wanaparthy:55:1|Nagarkurnool:nagarkurnool:55:1",
     "rangareddy|wanaparthy|nagarkurnool|narayanpet|jogulamba-gadwal|vikarabad",
     "Pillalamarri banyan tree, Somasila project, handloom weaving"),
    ("mancherial", "Mancherial", "HYD", 260,
     "Mancherial Bus Stand|Mancherial Railway Station|Bellampalli|Luxettipet",
     "Hyderabad:hyderabad:270:5|Adilabad:adilabad:80:1.5|Nirmal:nirmal:35:0.5|Karimnagar:karimnagar:85:2|Nagpur:nagpur:350:6",
     "adilabad|nirmal|kumuram-bheem-asifabad|peddapalli|jayashankar-bhupalpally",
     "Singareni coal mines, Bellampalli collieries, Pranahita River"),
    ("medak", "Medak", "HYD", 100,
     "Medak Bus Stand|Medak Town|Narsapur|Toopran",
     "Hyderabad:hyderabad:100:2|Sangareddy:sangareddy:40:1|Siddipet:siddipet:35:0.5|Nizamabad:nizamabad:90:2|Kamareddy:kamareddy:85:2",
     "sangareddy|siddipet|kamareddy|nizamabad|medchal-malkajgiri",
     "Medak Cathedral, largest church in Asia, Pochampally handlooms"),
    ("medchal-malkajgiri", "Medchal Malkajgiri", "HYD", 15,
     "Malkajgiri Bus Stand|Medchal|Kompally|Boduppal|Uppal",
     "Hyderabad:hyderabad:25:0.5|Secunderabad:secunderabad:15:0.5|Siddipet:siddipet:75:1.5|Sangareddy:sangareddy:55:1|Warangal:warangal:140:3",
     "hyderabad|rangareddy|sangareddy|siddipet|yadadri-bhuvanagiri",
     "Hyderabad suburb, IT corridor extension, Keesara temple"),
    ("mulugu", "Mulugu", "HYD", 230,
     "Mulugu Bus Stand|Mulugu Town|Medaram|Tadvai",
     "Warangal:warangal:80:2|Hyderabad:hyderabad:230:4|Bhadrachalam:bhadradri-kothagudem:100:2|Karimnagar:karimnagar:140:3|Khammam:khammam:120:2.5",
     "warangal|jayashankar-bhupalpally|bhadradri-kothagudem|mahabubabad",
     "Medaram Jatara (largest tribal fair), Laknavaram Lake, forests"),
    ("nagarkurnool", "Nagarkurnool", "HYD", 130,
     "Nagarkurnool Bus Stand|Nagarkurnool Town|Achampet|Kalwakurthy",
     "Hyderabad:hyderabad:140:3|Mahabubnagar:mahabubnagar:55:1|Srisailam:srisailam:70:1.5|Wanaparthy:wanaparthy:50:1|Kurnool:kurnool:170:3",
     "mahabubnagar|wanaparthy|jogulamba-gadwal|nalgonda",
     "Srisailam Dam gateway, Amrabad Tiger Reserve, Farahabad Fort"),
    ("nalgonda", "Nalgonda", "HYD", 80,
     "Nalgonda Bus Stand|Nalgonda Town|Devarakonda|Miryalguda",
     "Hyderabad:hyderabad:95:2|Suryapet:suryapet:55:1|Vijayawada:vijayawada:200:3.5|Warangal:warangal:130:2.5|Siddipet:siddipet:90:2",
     "suryapet|yadadri-bhuvanagiri|siddipet|rangareddy|jangaon",
     "Nagarjuna Sagar Dam, Panagal gardens, fluoride-free water project"),
    ("narayanpet", "Narayanpet", "HYD", 150,
     "Narayanpet Bus Stand|Narayanpet Town|Makthal|Utkoor",
     "Hyderabad:hyderabad:160:3|Mahabubnagar:mahabubnagar:65:1.5|Kurnool:kurnool:160:3|Raichur:raichur:130:2.5|Wanaparthy:wanaparthy:80:2",
     "mahabubnagar|wanaparthy|jogulamba-gadwal|kalaburagi",
     "Narayanpet handloom sarees, cotton weaving, Makthal temple"),
    ("nirmal", "Nirmal", "HYD", 270,
     "Nirmal Bus Stand|Nirmal Town|Bhainsa|Khanapur",
     "Hyderabad:hyderabad:280:5|Adilabad:adilabad:40:1|Mancherial:mancherial:35:0.5|Nizamabad:nizamabad:110:2|Karimnagar:karimnagar:120:2.5",
     "adilabad|mancherial|kumuram-bheem-asifabad|kamareddy|nizamabad",
     "Nirmal paintings (lacquer art), Basara Saraswati Temple, Sahastrakund"),
    ("nizamabad", "Nizamabad", "HYD", 150,
     "Nizamabad Bus Stand|Nizamabad Railway Station|Bodhan|Armoor",
     "Hyderabad:hyderabad:150:3|Karimnagar:karimnagar:110:2|Adilabad:adilabad:150:3|Kamareddy:kamareddy:35:0.5|Warangal:warangal:190:3.5",
     "kamareddy|nirmal|adilabad|medak|siddipet",
     "Turmeric city, Nizamabad Fort, Kanteshwar temple, Pochampally"),
    ("peddapalli", "Peddapalli", "HYD", 200,
     "Peddapalli Bus Stand|Peddapalli Railway Station|Ramagundam|Sultanabad",
     "Hyderabad:hyderabad:210:4|Karimnagar:karimnagar:25:0.5|Mancherial:mancherial:50:1|Warangal:warangal:90:2|Nizamabad:nizamabad:130:2.5",
     "karimnagar|mancherial|jayashankar-bhupalpally|jagtial|rajanna-sircilla",
     "Ramagundam thermal power, Godavarikhani coal mines, industrial hub"),
    ("rajanna-sircilla", "Rajanna Sircilla", "HYD", 140,
     "Sircilla Bus Stand|Sircilla Town|Vemulawada|Konaraopet",
     "Karimnagar:karimnagar:40:1|Hyderabad:hyderabad:150:3|Siddipet:siddipet:50:1|Warangal:warangal:85:2|Nizamabad:nizamabad:120:2.5",
     "karimnagar|siddipet|jagtial|kamareddy|peddapalli",
     "Vemulawada Rajanna Temple, textile town, powerloom capital"),
    ("rangareddy", "Rangareddy", "HYD", 20,
     "Shamshabad|Shadnagar|Ibrahimpatnam|Chevella|Rajendranagar",
     "Hyderabad:hyderabad:20:0.5|Bangalore:bangalore:550:8|Vijayawada:vijayawada:260:4.5|Mahabubnagar:mahabubnagar:80:1.5|Sangareddy:sangareddy:50:1",
     "hyderabad|medchal-malkajgiri|sangareddy|vikarabad|mahabubnagar|nalgonda",
     "Hyderabad IT corridor, Shamshabad airport area, pharma hub"),
    ("sangareddy", "Sangareddy", "HYD", 50,
     "Sangareddy Bus Stand|Sangareddy Town|Zaheerabad|Patancheru",
     "Hyderabad:hyderabad:55:1|Medak:medak:40:1|Siddipet:siddipet:65:1.5|Nizamabad:nizamabad:120:2.5|Kamareddy:kamareddy:100:2",
     "medak|medchal-malkajgiri|rangareddy|vikarabad|siddipet",
     "Patancheru industrial belt, Sangareddy Fort, Ameenpur heritage"),
    ("siddipet", "Siddipet", "HYD", 100,
     "Siddipet Bus Stand|Siddipet Town|Gajwel|Dubbak|Husnabad",
     "Hyderabad:hyderabad:100:2|Karimnagar:karimnagar:80:2|Warangal:warangal:90:2|Medak:medak:35:0.5|Sangareddy:sangareddy:65:1.5",
     "medak|karimnagar|rajanna-sircilla|jangaon|yadadri-bhuvanagiri|sangareddy",
     "Komati Cheruvu lake, turmeric market, handloom town"),
    ("suryapet", "Suryapet", "HYD", 130,
     "Suryapet Bus Stand|Suryapet Town|Kodad|Huzurnagar",
     "Hyderabad:hyderabad:140:3|Nalgonda:nalgonda:55:1|Vijayawada:vijayawada:150:3|Khammam:khammam:110:2|Warangal:warangal:140:2.5",
     "nalgonda|khammam|jangaon|yadadri-bhuvanagiri|ntr",
     "Mattapalli temple, pilgrimage town, rice and cotton trading"),
    ("vikarabad", "Vikarabad", "HYD", 60,
     "Vikarabad Bus Stand|Vikarabad Railway Station|Tandur|Pargi|Kodangal",
     "Hyderabad:hyderabad:70:1.5|Mahabubnagar:mahabubnagar:80:2|Sangareddy:sangareddy:60:1.5|Bangalore:bangalore:500:8|Raichur:raichur:280:5",
     "rangareddy|sangareddy|mahabubnagar|narayanpet",
     "Ananthagiri Hills, rock climbing, nature retreat near Hyderabad"),
    ("wanaparthy", "Wanaparthy", "HYD", 140,
     "Wanaparthy Bus Stand|Wanaparthy Town|Pebbair|Pangal",
     "Hyderabad:hyderabad:150:3|Mahabubnagar:mahabubnagar:55:1|Nagarkurnool:nagarkurnool:50:1|Kurnool:kurnool:150:3|Gadwal:jogulamba-gadwal:60:1.5",
     "mahabubnagar|nagarkurnool|jogulamba-gadwal|narayanpet",
     "Wanaparthy Palace, Priyadarshini Jurala Project, former princely state"),
    ("warangal", "Warangal", "HYD", 140,
     "Warangal Bus Stand|Warangal Railway Station|Warangal Fort|Bhadrakali",
     "Hyderabad:hyderabad:150:3|Hanumakonda:hanumakonda:12:0.5|Karimnagar:karimnagar:70:1.5|Khammam:khammam:110:2|Vijayawada:vijayawada:230:4",
     "hanumakonda|jangaon|mahabubabad|mulugu|siddipet",
     "Kakatiya dynasty capital, Warangal Fort, Ramappa Temple UNESCO site"),
    ("yadadri-bhuvanagiri", "Yadadri Bhuvanagiri", "HYD", 60,
     "Bhongir Bus Stand|Bhongir Railway Station|Yadagirigutta|Alair",
     "Hyderabad:hyderabad:65:1.5|Nalgonda:nalgonda:55:1|Warangal:warangal:110:2|Siddipet:siddipet:80:2|Suryapet:suryapet:80:2",
     "nalgonda|siddipet|jangaon|medchal-malkajgiri|suryapet",
     "Yadadri Lakshmi Narasimha Temple, Bhongir Fort, pilgrimage center"),
]

# ─── TELANGANA TOWNS ──────────────────────────────────────────────
TS_TOWNS = [
    ("secunderabad", "Secunderabad", "HYD", 30,
     "Secunderabad Junction Railway Station|Patny|Paradise Circle|Trimulgherry|Bowenpally",
     "Hyderabad:hyderabad:10:0.5|Warangal:warangal:150:3|Bangalore:bangalore:570:8|Vijayawada:vijayawada:275:5|Tirupati:tirupati:550:8",
     "hyderabad|medchal-malkajgiri|rangareddy|sangareddy",
     "Twin city of Hyderabad, major railway junction, cantonment area"),
]

# ─── PONDICHERRY ──────────────────────────────────────────────────
PY = "Pondicherry"
PY_DATA = [
    ("pondicherry", "Pondicherry", "MAA", 135,
     "Pondicherry Bus Stand|Pondicherry Railway Station|Promenade Beach|Auroville|White Town",
     "Chennai:chennai:150:3|Cuddalore:cuddalore:25:0.5|Villupuram:villupuram:35:0.5|Mahabalipuram:mahabalipuram:95:2|Trichy:trichy:210:4|Bangalore:bangalore:310:5.5",
     "villupuram|cuddalore|chengalpattu|tiruvannamalai",
     "French colonial heritage, Auroville, Promenade Beach, spiritual tourism"),
    ("karaikal", "Karaikal", "TRZ", 130,
     "Karaikal Bus Stand|Karaikal Port|Karaikal Beach",
     "Nagapattinam:nagapattinam:20:0.5|Thanjavur:thanjavur:80:2|Trichy:trichy:150:3|Pondicherry:pondicherry:135:3|Chennai:chennai:300:5",
     "nagapattinam|thanjavur|mayiladuthurai|velankanni",
     "French enclave, Karaikal Beach, Karaikal Ammaiyar Temple"),
    ("mahe", "Mahe", "CCJ", 60,
     "Mahe Bus Stand|Mahe River Bridge|Mahe Town",
     "Kozhikode:kozhikode:60:1.5|Kannur:kannur:50:1|Wayanad:wayanad:100:2|Mangalore:mangalore:200:4|Bangalore:bangalore:380:6.5",
     "kozhikode|kannur|wayanad",
     "Smallest district of Pondicherry, French heritage on Malabar coast"),
    ("yanam", "Yanam", "VGA", 180,
     "Yanam Bus Stand|Yanam Town|Yanam River",
     "Kakinada:kakinada:20:0.5|Rajahmundry:rajahmundry:60:1.5|Vijayawada:vijayawada:200:3.5|Vizag:vizag:200:4|Hyderabad:hyderabad:480:8",
     "kakinada|east-godavari|konaseema",
     "French enclave in AP, Yanam Godavari riverfront, smallest UT district"),
]

# ─── BUILD FULL LIST ──────────────────────────────────────────────
all_districts = []
for d in TN_DATA:
    all_districts.append(make_entry(d[0], d[1], TN, "TN", d[2], d[3], d[4], d[5], d[6], d[7]))
for d in TN_TOWNS:
    all_districts.append(make_entry(d[0], d[1], TN, "TN", d[2], d[3], d[4], d[5], d[6], d[7]))
for d in KL_DATA:
    all_districts.append(make_entry(d[0], d[1], KL, "KL", d[2], d[3], d[4], d[5], d[6], d[7]))
for d in KL_TOWNS:
    all_districts.append(make_entry(d[0], d[1], KL, "KL", d[2], d[3], d[4], d[5], d[6], d[7]))
for d in KA_DATA:
    all_districts.append(make_entry(d[0], d[1], KA, "KA", d[2], d[3], d[4], d[5], d[6], d[7]))
for d in KA_TOWNS:
    all_districts.append(make_entry(d[0], d[1], KA, "KA", d[2], d[3], d[4], d[5], d[6], d[7]))
for d in AP_DATA:
    all_districts.append(make_entry(d[0], d[1], AP, "AP", d[2], d[3], d[4], d[5], d[6], d[7]))
for d in AP_TOWNS:
    all_districts.append(make_entry(d[0], d[1], AP, "AP", d[2], d[3], d[4], d[5], d[6], d[7]))
for d in TS_DATA:
    all_districts.append(make_entry(d[0], d[1], TS, "TS", d[2], d[3], d[4], d[5], d[6], d[7]))
for d in TS_TOWNS:
    all_districts.append(make_entry(d[0], d[1], TS, "TS", d[2], d[3], d[4], d[5], d[6], d[7]))
for d in PY_DATA:
    all_districts.append(make_entry(d[0], d[1], PY, "PY", d[2], d[3], d[4], d[5], d[6], d[7]))

# ─── WRITE JSON ───────────────────────────────────────────────────
out_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data", "districts-data.json")
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(all_districts, f, indent=2, ensure_ascii=False)

print(f"Generated {len(all_districts)} district entries to {out_path}")
